"""add_source_and_new_status

Revision ID: 03162ba0df2b
Revises: 43acf6ad0044
Create Date: 2026-01-06 12:25:27.245531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '03162ba0df2b'
down_revision: Union[str, Sequence[str], None] = '43acf6ad0044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('expiry_date', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'expiry_date')
    # ### end Alembic commands ###
