"""add email draft and reject node

Revision ID: 42b0e45733a8
Revises: 8d5ce6e43f88
Create Date: 2026-01-05 10:12:06.353480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42b0e45733a8'
down_revision: Union[str, Sequence[str], None] = '8d5ce6e43f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('email_draft', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('task_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'task_link')
    op.drop_column('applications', 'email_draft')
    # ### end Alembic commands ###
