"""add email draft and reject node

Revision ID: af07cf1c1fa0
Revises: 42b0e45733a8
Create Date: 2026-01-05 10:43:51.987257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'af07cf1c1fa0'
down_revision: Union[str, Sequence[str], None] = '42b0e45733a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('candidate_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('applications', sa.Column('candidate_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('applications', sa.Column('is_email_sent', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_applications_candidate_email'), 'applications', ['candidate_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_candidate_email'), table_name='applications')
    op.drop_column('applications', 'is_email_sent')
    op.drop_column('applications', 'candidate_phone')
    op.drop_column('applications', 'candidate_email')
    # ### end Alembic commands ###
